version: '3.1'

services:
  pivot-demo-db:
    image: postgres:14
    container_name: pivot-demo-db
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=pivot_demo
    ports:
      - "5437:5432"
